### PR TITLE
InfoStringOfInstalledOperationsOfCategory now shows further mathematical properties

### PR DESCRIPTION
**Pull request by mohamed-barakat**
the motivation behind this is two-fold:
1. To see the categorical properties which are not linked to CAP operations
2. To see which constructive categorical properties are mathematically valid but not yet constructive

### CODE REVIEW

**Review by zickgraf — APPROVED** [review]
modulo test failures.

Also I will request a review from @sebastianpos to check whether he is okay with the new format (@sebastianpos: A quick look at the examples in the diff is sufficient.)

**Comment by sebastianpos** [comment]
Could you explain:

> mathematically but not yet algorithmically

vs

> mathematically

?

**Comment by mohamed-barakat** [comment]
For a property `P`

"mathematically" means: 
1. the property is added using AddCategoricalProperty

"mathematically but not yet algorithmically" means
1. P was added using AddCategoricalProperty
2. there exists a corresponding entry in the record `CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD`, so `CheckConstructivenessOfCategory` applied to this property will not issue an error.
3. `not IsEmpty( CheckConstructivenessOfCategory( cat, P ) )` 

I can add such explanations to the commit message or to the code. Whatever you prefer.

**Comment by sebastianpos** [comment]
Thank you.

No, I think having your explanation here in this thread suffices. It appears to be a feature for programmers who are already quite deep into implementing categories.

**Review by sebastianpos — APPROVED** [review]

**Pull request merged**
