### PR TITLE
Include documentation for family properties

### PR DESCRIPTION
**Pull request by zickgraf**
This needs a recent AutoDoc version. The relevant AutoDoc-PR is https://github.com/gap-packages/AutoDoc/pull/234 (not yet merged).

I assume that the `TODO` comments were referring to the fact that the comments were not picked up by AutoDoc.

### CODE REVIEW

**Comment by sebastianpos** [comment]
I think it would be wiser to simply get rid of the `DeclareFamilyProperty` concept in CAP. As far as I can see, it has no real implications anymore.

**Comment by zickgraf** [comment]
Ah, I did not actually look at what `DeclareFamilyProperty` does. Should it suffice to replace `DeclareFamilyProperty` by `DeclareProperty` while dropping the additional arguments? If yes, I would update this PR accordingly.

**Comment by sebastianpos** [comment]
I think so, yes.

Later, I can take care of deleting all the code implementing "family properties".

**Comment by zickgraf** [comment]
I have replaced all occurrences of `DeclareFamilyProperty` by `DeclareProperty` and the CI is green, so this is ready for review :-)

**Comment by sebastianpos** [comment]
Thank you :-)

**Pull request merged**
