### PR TITLE
Fix derivation of IsDominating

### PR DESCRIPTION
**Pull request by zickgraf**
The dual version

https://github.com/homalg-project/CAP_project/blob/27ad4ab68123184d4a026803b69dc0fe0024bf1d/CAP/gap/DerivedMethods.gi#L1661-L1675

seems to be correct, that's how I discovered this problem. But I may be wrong. @sebastianpos Could you double-check this? It's very easy to make mistakes with these things :D

### CODE REVIEW

**Comment by zickgraf** [comment]
I have verified this using an example:
```
LoadPackage( "LinearAlgebraForCAP" );

is_dominating1 := function( cat, sub1, sub2 )
    
    return IsLiftableAlongMonomorphism( cat, sub2, sub1 );
    
end;

is_dominating2 := function( cat, sub1, sub2 )
    local cokernel_projection_1, cokernel_projection_2;
    
    cokernel_projection_1 := CokernelProjection( cat, sub1 );
    
    cokernel_projection_2 := CokernelProjection( cat, sub2 );
    
    return IsCodominating( cat, cokernel_projection_1, cokernel_projection_2 );
    
end;

is_dominating3 := function( cat, sub1, sub2 )
    local cokernel_projection_1, cokernel_projection_2;
    
    cokernel_projection_1 := CokernelProjection( cat, sub1 );
    
    cokernel_projection_2 := CokernelProjection( cat, sub2 );
    
    return IsCodominating( cat, cokernel_projection_2, cokernel_projection_1 );
    
end;

QQ := HomalgFieldOfRationals( );
cat := MatrixCategory( QQ );

alpha := HomalgMatrix( [ 1, 0 ], 1, 2, QQ ) / cat;
beta := IdentityMorphism( 2 / cat );

Display( "1:" );
Display( is_dominating1( cat, alpha, beta ) );
Display( is_dominating1( cat, beta, alpha ) );

Display( "2:" );
Display( is_dominating2( cat, alpha, beta ) );
Display( is_dominating2( cat, beta, alpha ) );

Display( "3:" );
Display( is_dominating3( cat, alpha, beta ) );
Display( is_dominating3( cat, beta, alpha ) );
```

`is_dominating2` is the old derivation from `IsCodominating`, `is_dominating3` is the version in this PR. The latter gives the expected result.

**Comment by mohamed-barakat** [comment]
Very nice!

**Review by sebastianpos — COMMENTED** [review]
Yes, changing the 2 arguments is correct. Thank you.

I wonder why there is no assumption for this deriviation (like being abelian). In general, there is no 1:1 correspondence between subobjects and quotient objects.

**Comment by zickgraf** [comment]
> I wonder why there is no assumption for this deriviation (like being abelian). In general, there is no 1:1 correspondence between subobjects and quotient objects.

You are right, I simply looked at the diagrams but did not check that the lifts/colifts actually exist. Shall I simply remove the derivation? I guess in almost all categories the derivations from `LiftAlongMonomorphism` will be used anyway.

**Comment by sebastianpos** [comment]
You can either remove it or implement the assumption that the underlying category is abelian.

**Comment by zickgraf** [comment]
Done: https://github.com/homalg-project/CAP_project/pull/1486 :-)

**Pull request merged**
