### PR TITLE
New component functorial

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by sebasguts** [comment]
We can add this component without any problem, there will not be any compatibility problem.

We could also generate this entry automatically, what could keep us from forgetting to set it for other methods.

At the moment, this entry is not documented. The right place to document it is the `InstallAdds.autodoc`, where all method record entries are documented (also automatically generated ones).

**Comment by sebastianpos** [comment]
I think for an automatic generation of these entries,
the naming convention has to be changed as follows:

-  `CokernelFunctorial` -> `CokernelObjectFunctorial`
- `KernelObjectFunctorial` stays as it was

With this convention, all entries of the form
`XFunctorial`
would have 
X = name of the function that gives the object of the universal construction,
e.g.,
`TerminalObjectFunctorial,` `DirectSumFunctorial`, etc.

**Comment by mohamed-barakat** [comment]
I agree.

**Comment by sebasguts** [comment]
We can associate `KernelFunctorial` to `KernelObject`, as long as the rule is to drop the `Object` in all cases. For consistent and very descriptive naming in `CAP` we could also go to `CokernelObjectFunctorial`, for me both is fine.

**Pull request closed without merging**
