### PR TITLE
Refactor sanity checks

### PR DESCRIPTION
**Pull request by zickgraf**
See commit messages for details.

### CODE REVIEW

**Comment by zickgraf** [comment]
This PR will possibly break categories returning `fail` for `IsEqualForObjects` etc. This should be handled as part of #621: If we do not allow `IsEqualForObjects` to return `fail` when installing it via `AddIsEqualForObjects`, this PR is actually fine. If we allow this, I will introduce another return type `bool_or_fail`.

**Comment by sebastianpos** [comment]
I get the following error:
```
gap> LoadPackage( "Freyd" );
Error, the return_type of <current_rec> is not a filter and does not appear in CAP_INTERNAL_VALID_RETURN_TYPES
```

**Comment by zickgraf** [comment]
Can you type `current_rec` to see which record is affected? I assume it's this issue: https://github.com/homalg-project/HigherHomologicalAlgebra/issues/25 Then you can simply update `HigherHomologicalAlgebra` :-)

**Review by sebastianpos — APPROVED** [review]
Works, thank you.

**Pull request merged**
