### PR TITLE
use TensorProductToInternal(Co)HomAdjunctionMapWithGivenInternal(Co)Hom

### PR DESCRIPTION
**Pull request by mohamed-barakat**
instead of TensorProductToInternal(Co)HomAdjunctionMap at various places

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Preparing for the upcoming `PreComposeList`-PR.

**Comment by mohamed-barakat** [comment]
@zickgraf: Only the weights have changed as expected, but not the compiled code.

**Comment by zickgraf** [comment]
> @zickgraf: Only the weights have changed as expected, but not the compiled code.

That's fine :-)

**Comment by mohamed-barakat** [comment]
For the records: All tests in `LazyCategories` pass. After merging this PR I will trigger a general test in `CategoricalTowers`.

**Comment by mohamed-barakat** [comment]
Now [testing](https://github.com/homalg-project/CategoricalTowers/actions/runs/5867797136) `CategoricalTowers`.

**Comment by mohamed-barakat** [comment]
> Now [testing](https://github.com/homalg-project/CategoricalTowers/actions/runs/5867797136) `CategoricalTowers`.

The test passed.

**Pull request merged**
