### PR TITLE
added rule IsIsomorphism( a ) => IsIsomorphism( Inverse( a ) )

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by sebasguts** [comment]
What happened here?

**Comment by mohamed-barakat** [comment]
1. I updated my mohamed-barakat:CAP_project/master by merging your stuff with kamal's an mine. And since I sent you a merge request from this branch back in September, you got a notification that the pull-request got updated.

2. Then I mistakenly updated homalg-project:CAP_project/master. This caused the pull-request to be marked as merged. I just reseted homalg-project:CAP_project/master to your status. Sorry.

**Comment by sebasguts** [comment]
Okay, thank you :). Github automatically updates PRs if something is merged to the branch.

**Comment by mohamed-barakat** [comment]
Exactly. This "feature" was added at some point.

**Pull request merged**
