### PR TITLE
Merge the terminal categories

### PR DESCRIPTION
**Pull request by TKuh**
I closed https://github.com/homalg-project/CAP_project/pull/1009 by accidentally removing my branch and force-pushed, so I can't reopen it... sorry.

### CODE REVIEW

**Review by zickgraf — APPROVED** [review]
I have some minor suggestions but will include those myself in a follow-up PR with some more modifications going beyond the scope of this PR.

Thanks a lot! This has turned out to be more intricate than expected.

**Comment by zickgraf** [comment]
In TerminalCategory.gd there are two chunks insterted:

```
#! @InsertChunk TerminalCategory
...
#! @InsertChunk TerminalCategoryWithMultipleObjects
```

Do you have an example file which you forgot to commit?

**Comment by TKuh** [comment]
No, it was probably a copy paste mistake.

**Comment by zickgraf** [comment]
@mohamed-barakat As expected, this makes the code coverage drop in MonoidalCategories and CartesianCategories because fewer operations are installed for the terminal category: https://codecov.io/gh/homalg-project/CAP_project/compare/b4f2cfc16cf7b89742192cc375e074bceab71a4b...eb5f7e9702d6bc9d90ea515e79eb66bbfc35765e/changes As discussed, there are two possibilities for increasing the coverage again:
1. Extend CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD in MonoidalCategories.
2. Implement a mechanism for registering operations for installation in the terminal category.

**Pull request merged**
