### PR TITLE
Comply with https://github.com/homalg-project/homalg_project/pull/479

### PR DESCRIPTION
**Pull request by kamalsaleh**

### CODE REVIEW

**Comment by kamalsaleh** [comment]
It must be caused by:

https://github.com/homalg-project/CapAndHomalg.jl/blob/b6bbc5bd5e502b87cf2c87be4fe3f9ec833b27d4/src/CapAndHomalg.jl#L81-L82
```
Base.show(io::IO, ::MIME"application/x-latex", obj::GapObj) = print(io, string("\$\$", String(GAP.Globals.LaTeXStringOp(obj))), "\$\$")
Base.show(io::IO, ::MIME"text/latex", obj::GapObj) = print(io, string("\$\$", String(GAP.Globals.LaTeXStringOp(obj))), "\$\$")
```

Consequently, applying the changes to FreydCategoriesForCAP alone may permit all packages to load, but the tests will still fail. 

I will create a PR in CapAndHomalg  to comply with the changes in homalg.

**Comment by zickgraf** [comment]
Thanks a lot for this analysis!

**Comment by zickgraf** [comment]
There are still errors in InternalModules:
```
553,555c553
<        "$$\\left( \\begin{array}{rrr}\n",
<        " 1 & \\cdot & \\cdot \n",
<        "\\end{array} \\right) 𝟙^{\\{1\\}}$$"
---
>        "$$<object>$$"
587,589c585
<        "$$\\left( \\begin{array}{rrr}\n",
<        " \\cdot & 1 & \\cdot \n",
<        "\\end{array} \\right) 𝟙^{\\{1\\}}$$"
---
>        "$$<object>$$"
...
```

https://github.com/homalg-project/InternalModules/runs/7112243389

**Comment by kamalsaleh** [comment]
I have created a PR, see https://github.com/homalg-project/InternalModules/pull/24

**Pull request merged**
