### PR TITLE
Validate limits in the method record

### PR DESCRIPTION
**Pull request by zickgraf**
I have written a function `CAP_INTERNAL_ADD_LIMIT_COLIMIT_PAIR` which takes a specification of a diagram shape as an input and automatically generates the entries of the method record for limits of diagrams of this shape (and for colimits of diagrams of the opposite shape). E.g.,
```
CAP_INTERNAL_ADD_LIMIT_COLIMIT_PAIR( [ "fixedobject", "varobject" ], [ [ 2, "varmorphism", 1 ] ], "FiberProduct", "ProjectionInFactorOfFiberProduct", "UniversalMorphismIntoFiberProduct", "Pushout", "InjectionOfCofactorOfPushout", "UniversalMorphismFromPushout" );
```
generates the entries `FiberProduct`, `ProjectionInFactorOfFiberProduct` and `UniversalMorphismIntoFiberProduct` (including pre functions), the `WithGiven` versions, the functorial, and the corresponding duals. Currently, this works for `DirectProduct`, `DirectSum`, `FiberProduct`, `Equalizer`, `KernelObject`, `TerminalObject`, `InitialObject` and `ZeroObject` (and the corresponding projections, universal morphisms etc.).

I started this as a tool for making the method record and, in particular, the pre functions (more) consistent, but now I think it could be a useful addition to CAP. If you agree, I have a few questions:

1. Should this work like a preprocessor, i.e. an external tool which generates code which in turn is copy-pasted into the method record, or should it be part of CAP and generate the entries of the method record when CAP is loaded? I would prefer the second option.
2. I have not yet compared the performance of the generated pre functions to the performance of the hand-written ones. Is a "small" performance hit acceptable or is it a strict requirement that the generated pre functions are not slower than hand-written ones?
3. What would be the correct place for documenting internal stuff like this (for example the diagram specification and parsing rules)?

Of course, I also want to use this for #158. In particular, the function `DiagramGenerator` proposed in #162 can now be automatically generated and the "hackiness" in #162 is solved.

### CODE REVIEW

**Comment by sebastianpos** [comment]
This looks very impressive and I need more understanding :-)

Concerning your third question:
We have a chapter in the documentation of the internals of
Add functions:
https://github.com/homalg-project/CAP_project/blob/master/CAP/doc/AddFunctions.autodoc
I think this might be a good place for your documentation.
In particular, I am interested in the documentation of
the command `CAP_INTERNAL_ADD_LIMIT_COLIMIT_PAIR`
since I find it difficult to interpret its first two arguments.

Maybe you could write a small section on this command. I think this
will make it easier for me to see your overall plan and it will facilitate
the review.

**Comment by zickgraf** [comment]
I have decided to split this PR into multiple PRs to simplify discussion and review. Now, this PR only includes the validation of the method record. The addition of prefunctions etc. will go into separate PRs. Note that this PR depends on https://github.com/homalg-project/CAP_project/pull/206 and https://github.com/homalg-project/CAP_project/pull/212, i.e. only the last commit is relevant.

I have changed the structure in comparison to the first version for the following reason:

I want to use the information about limits for three things:

1. Validate the entries of the method record.
2. Generate prefunctions automatically.
3. Generate derivations automatically.

These three things cannot be done at the same time (prefunctions have to be added before enhancing the method record, derivations have to be added after the Adds are installed, if I understand correctly). Thus, the information about limits is now contained in the global list `CAP_INTERNAL_METHOD_NAME_RECORD_LIMITS`. The entries can be enhanced (similar to the method record) by calling the global function `CAP_INTERNAL_ENHANCE_NAME_RECORD_LIMITS`. The validation is done by the global function `CAP_INTERNAL_VALIDATE_LIMITS_IN_NAME_RECORD`.


Note 1: I have not implemented @sebasguts's suggestion of attaching the information about limits directly to the method record since I am not sure what the right way to do this is. I think putting it under `CAP_INTERNAL_METHOD_NAME_RECORD.limits` is not possible since then a method `limits` would be expected.

Note 2: In the documentation I overload some notions with multiple meanings. For example, an object can be a concrete object in a diagram but also a string "varobject" which actually stands for mutiple objects. This is done intentionally to better convey the basic idea, but if it is confusing I can of course make this more precise.

All in all, this is now ready for review.

**Comment by zickgraf** [comment]
Note that this PR includes the proposed fix in #187.

**Comment by zickgraf** [comment]
I accidentally did a force push here. Please ignore this, I have force-pushed again to the correct commit 4e5d07f.

**Pull request merged**
