### PR TITLE
Remove superfluous special cases in CategoryOfRows/Columns

### PR DESCRIPTION
**Pull request by zickgraf**
ConvertMatrixFrom/ToRow/Column should be able to handle empty matrices without problems.

@mohamed-barakat Can you confirm this statement?

### CODE REVIEW

**Review by mohamed-barakat — APPROVED** [review]
Yes, I had these corner cases in mind when I wrote the Convert* commands and tested them all. So I assume they still work.

**Review by sebastianpos — APPROVED** [review]
This code is much nicer and appears to work :)

**Comment by mohamed-barakat** [comment]
I now remember why I did not do this simplification, although they would behave correctly worked (sorry, this was not present in my mind when I saw the PR). I wanted to go through the cache of `UniversalMorphismIntoZeroObject` and `ZeroMorphism` in the corner cases to avoid constructing new morphisms. Maybe these premature optimization ideas are slowly becoming obsolete with `CompilerForCAP`.

**Comment by zickgraf** [comment]
> I wanted to go through the cache of `UniversalMorphismIntoZeroObject` and `ZeroMorphism` in the corner cases to avoid constructing new morphisms.

According to https://github.com/homalg-project/CAP_project/issues/594#issuecomment-698805777, Rows/Cols/MatrixCategory should be workhorse categories not relying on caching extensively. So if one wants/needs the caching, one probably has to adapt the category anyway, I assume.

**Comment by mohamed-barakat** [comment]
I am happy with this :)

**Pull request merged**
