### PR TITLE
Fix dual_pre_processor_func for `TensorProductOnMorphisms`

### PR DESCRIPTION
**Pull request by TKuh**
Credit to @zickgraf. Was found via [here](https://github.com/homalg-project/CAP_project/issues/886).

### CODE REVIEW

**Comment by zickgraf** [comment]
I think this pattern (keep the order of the actual arguments but swap the given source and range) occurs at many places, right? We could introduce a switch `dual_with_given_objects_reversed` (or even make this the default for operations with given source and range).

**Comment by TKuh** [comment]
Oh yes, it occurs _very_ often. Such a switch would be very helpful (if it doesn't bloat the method records, it seems to me that they can become already quite chaotic?).

**Comment by zickgraf** [comment]
> Oh yes, it occurs _very_ often. Such a switch would be very helpful (if it doesn't bloat the method records, it seems to me that they can become already quite chaotic?).

It's not more bloat than having two write a custom preprocessor function I think :D I suggest we implement this together during the next meeting, so you see the relevant code and can implement similar changes yourself in the future. Could you check if this actually occurs for *all* operations with `with_given_object_position := "both"` (both inside and outside of `MonoidalCategories`)? If yes, we could just make this the default.

And another thing: if the dual version of the tensor product would swap its arguments, we could simply use `dual_arguments_reversed`. What would be the implications of doing so? Would it make the code at other places (e.g. the internal hom adjunctions) easier or more complicated?

**Comment by mohamed-barakat** [comment]
For me, this PR is ready for merge. Is there more discussion needed before merging?

**Comment by zickgraf** [comment]
> For me, this PR is ready for merge. Is there more discussion needed before merging?

It's ready to merge, my suggestion should be part of a separate PR.

**Comment by mohamed-barakat** [comment]
@TKuh: Is there anything analogous that must be done for `Toposes`?

**Comment by TKuh** [comment]
> > Oh yes, it occurs _very_ often. Such a switch would be very helpful (if it doesn't bloat the method records, it seems to me that they can become already quite chaotic?).
> 
> It's not more bloat than having two write a custom preprocessor function I think :D 

Touché. :)

> I suggest we implement this together during the next meeting, so you see the relevant code and can implement similar changes yourself in the future. Could you check if this actually occurs for _all_ operations with `with_given_object_position := "both"` (both inside and outside of `MonoidalCategories`)? If yes, we could just make this the default.

Yes, that might be very helpful for the future. I'll look into it.

> And another thing: if the dual version of the tensor product would swap its arguments, we could simply use `dual_arguments_reversed`. What would be the implications of doing so? Would it make the code at other places (e.g. the internal hom adjunctions) easier or more complicated?

That would be mathematically wrong. :(
The dual of 
```
        f x g
a x b ----------> c x d
```
should be
```
          (f x g)^op
a x b <----------------- c x d
```
and not
```
           (g x f)^op
b x a <----------------- d x c
```
At least if we want `Opposite` to behave in the way one would expect it mathematically. And I think a couple of months ago when all of this dualization work started (left/right internal (co)homs etc.) we agreed, that opposite should work the way it does now.

**Comment by TKuh** [comment]
> @TKuh: Is there anything analogous that must be done for `Toposes`?

Yes, the same mistake happens with `DirectProductOnMorphismsWithGivenDirectProducts` and `CoproductOnMorphismsWithGivenCoproducts`. I will fix it.

**Comment by TKuh** [comment]
> > Oh yes, it occurs _very_ often. Such a switch would be very helpful (if it doesn't bloat the method records, it seems to me that they can become already quite chaotic?).
> 
> It's not more bloat than having two write a custom preprocessor function I think :D I suggest we implement this together during the next meeting, so you see the relevant code and can implement similar changes yourself in the future. Could you check if this actually occurs for _all_ operations with `with_given_object_position := "both"` (both inside and outside of `MonoidalCategories`)? If yes, we could just make this the default.

Ok, so I checked in the method records of `CAP/gap/MethodRecord.gi` and in `MonoidalCategories` how the operations with `'with_given_object_position := "both"` handle the dual operation and actually almost all the time `dual_arguments_reversed` is used (instead of a custom dual_pre/post_function).
For `MonoidalCategories` the only exceptions where dual_pre_functions are used, are

- TensorProductOnMorphisms
- The associators
- The compatibility morphisms (really not surprising, they are complicated)
- MorphismFromInternalHomToTensorProduct
- MorphismFromTensorProductToInternalCoHom

For CAP, the exceptions are

- HomomorphismStructureOnMorphisms
- InterpretMorphismAsMorphismFromDistinguishedObjectToHomomorphismStructure
- MorphismBetweenDirectSums

So I take back my initial enthusiasm; I don't think a switch `dual_with_given_objects_reversed` is necessary. In almost all cases one can use `dual_arguments_reversed`. The monoidal operations above are really only special cases, where reversing all arguments doesn't work.

**Pull request merged**
