### PR TITLE
Caching in MatrixCategory

### PR DESCRIPTION
**Pull request by sebastianpos**
I would like to discuss the caching in `MatrixCategory`.

Since this category is supposed to be a "work horse", it think caching (as provided by `ToolsForHomalg)` should be kept to a minimum. This is why I suggest to delete it from the current object and morphism constructors.

However, there is a cheap way to cache objects via `KeyDependentOperation`, which I suggest to incorporate into the current implementation.

### CODE REVIEW

**Comment by sebastianpos** [comment]
If there are no concerns then I will merge this PR in one week.

**Comment by mohamed-barakat** [comment]
I think it is a good idea, in principle. I just would've wished we have an extensive functioning CI so that we are able to test possible regressions. This is how Markus and I were able to handle regressions after such subtle changes in homalg.

@zickgraf Is travis/circle-ci able to log timings/report regressions?

**Comment by mohamed-barakat** [comment]
I now think the use of `KeyDependentOperation` should even be faster than caching.

**Comment by zickgraf** [comment]
> Is travis/circle-ci able to log timings/report regressions?

I'm not aware of such a feature. CircleCI  logs build times but they vary quite a bit: https://circleci.com/build-insights/gh/homalg-project

**Pull request merged**
