### PR TITLE
allow compiling standardly wrapped categories

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by zickgraf** [comment]
How urgent is this for you? I can probably look into supporting operations instead of functions properly in CompilerForCAP, but maybe not before the weekend.

**Comment by mohamed-barakat** [comment]
Only needed when compiling  CategoryOfQuivers, so not urgent.

**Comment by zickgraf** [comment]
@mohamed-barakat This should be fixed by #1028. Can you check?

**Comment by mohamed-barakat** [comment]
Yes, indeed, fixed by #1028.

**Comment by mohamed-barakat** [comment]
Thank you very much.

**Pull request closed without merging**
