### PR TITLE
renamed InverseMorphismFromCoimageToImage* -> InverseOfMorphismFromCoimageToImage*

### PR DESCRIPTION
**Pull request by mohamed-barakat**
and switched the order of arguments

resolves https://github.com/homalg-project/CAP_project/issues/1483

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Should be rebased onto https://github.com/homalg-project/CAP_project/pull/1482. I just wanted to free my stack.

**Comment by mohamed-barakat** [comment]
`FreydCategoriesForCAP` is failing since the mechanism that counts the number of CAP operations per derivation does not take synonyms into account. In this case, the derivation is in `Toposes` and uses the synonym (=old name) `InverseMorphismFromCoimageToImageWithGivenObjects`.

**Comment by zickgraf** [comment]
> `FreydCategoriesForCAP` is failing since the mechanism that counts the number of CAP operations per derivation does not take synonyms into account. In this case, the derivation is in `Toposes` and uses the synonym (=old name) `InverseMorphismFromCoimageToImageWithGivenObjects`.

`Toposes` is not loaded in the CAP_project CI, so this cannot be the culprit. Also, the synonym is wrong because the arguments are swapped. In this case, I suggest to not provide backwards compatibility to explicitly draw attention to the fact that the arguments are now swapped.

**Comment by mohamed-barakat** [comment]
> `Toposes` is not loaded in the CAP_project CI, so this cannot be the culprit.

I falsely assumed that the CAP_project tests would work on my laptop as they do in the GitHub CI.

```gap
Executing with non-reversed RecNames
Architecture: aarch64-apple-darwin21-default64-kv8

testing: /Users/mo/.gap/pkg/CAP_project/FreydCategoriesForCAP//tst/050_load_with_suggested_dependencies.tst
########> Diff in /Users/mo/.gap/pkg/CAP_project/FreydCategoriesForCAP//tst/050_load_with_suggested_dependencies.tst:8
# Input is:
LoadPackage( "FreydCategoriesForCAP", false );
# Expected output:
true
# But found:
Error, Variable: 'InverseMorphismFromCoimageToImageWithGivenObjects' must have\
 a value
Syntax warning: Unbound global variable in /Users/mo/.gap/pkg/CategoricalTower\
s/Toposes//gap/ToposDerivedMethods.gi:1048
    iso := InverseMorphismFromCoimageToImageWithGivenObjects( cat, coimage, mo\
r, image );
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error, was not in any namespace
Error, was not in any namespace
########
########> Diff in /Users/mo/.gap/pkg/CAP_project/FreydCategoriesForCAP//tst/050_load_with_suggested_dependencies.tst:11
# Input is:
LoadPackage( "FreydCategoriesForCAP" );
# Expected output:
true
# But found:
#I  Toposes: Do not call `LoadPackage( "freydcategoriesforcap", ... )' in the package file
```

> Also, the synonym is wrong because the arguments are swapped. In this case, I suggest to not provide backwards compatibility to explicitly draw attention to the fact that the arguments are now swapped.

Done.

**Pull request merged**
