### PR TITLE
Rename IsIdenticalToIdentity/ZeroMorphism to IsEqualToIdentity/ZeroMorphism and deprecate CokernelFunctorial in favor of CokernelObjectFunctorial

### PR DESCRIPTION
**Pull request by zickgraf**
@sebastianpos Are those two changes okay? (You do not have to look at the code, there is nothing special.)

### CODE REVIEW

**Comment by sebastianpos** [comment]
Yes, I'm ok with the renaming. I cannot find a reason why it was `IsIdentical` instead of `IsEqual`

**Comment by zickgraf** [comment]
> Yes, I'm ok with the renaming. I cannot find a reason why it was `IsIdentical` instead of `IsEqual`

I assume because `IsEqualForMorphisms` and `IsCongruentForMorphisms` were previously called `IsIdenticalForMorphisms` and `IsEqualForMorphisms`: 427e224b4c8e8ab71d7ae2de823c31e6ee2b66ee.

**Comment by zickgraf** [comment]
Addendum: Thanks for the fast reply!

**Comment by sebastianpos** [comment]
> I assume because `IsEqualForMorphisms` and `IsCongruentForMorphisms` were previously called `IsIdenticalForMorphisms` and `IsEqualForMorphisms`: [427e224](https://github.com/homalg-project/CAP_project/commit/427e224b4c8e8ab71d7ae2de823c31e6ee2b66ee).

This is a good explanation. Thanks.

**Pull request merged**
