### PR TITLE
installed derivations for Abelian categories

### PR DESCRIPTION
**Pull request by mohamed-barakat**
* IsomorphismFromImageObjectToKernelOfCokernel
* IsomorphismFromKernelOfCokernelToImageObject
* IsomorphismFromCoimageToCokernelOfKernel
* IsomorphismFromCokernelOfKernelToCoimage

### CODE REVIEW

**Comment by zickgraf** [comment]
Your derivation of IsomorphismFromImageObjectToKernelOfCokernel should already be covered by the following two derivations:

https://github.com/homalg-project/CAP_project/blob/e81d51f4bccf1b181d2083cc5f2f0757976d1fa1/CAP/gap/DerivedMethods.gi#L1913-L1924
https://github.com/homalg-project/CAP_project/blob/e81d51f4bccf1b181d2083cc5f2f0757976d1fa1/CAP/gap/DerivedMethods.gi#L863-L872

The derivation of IsomorphismFromKernelOfCokernelToImageObject should be covered in a dual way (see https://github.com/homalg-project/CAP_project/issues/977 for the generic issue for this).

**Comment by mohamed-barakat** [comment]
I see, thanks for clarifying. I will close this PR for now and rebase the next on`master`.

**Comment by zickgraf** [comment]
@mohamed-barakat Could you revive this PR this week according to https://github.com/homalg-project/CAP_project/pull/1197#issuecomment-1346561257 before the context is lost over the holidays?

**Comment by mohamed-barakat** [comment]
Yes, this is on my todo-list for the week

**Comment by mohamed-barakat** [comment]
I should have reopened and then force-pushed. Now I cannot reopen the PR.

**Pull request closed without merging**
