### PR TITLE
host TerminalCategoryWithMultipleObjects

### PR DESCRIPTION
**Pull request by mohamed-barakat**
which was outsourced from CategoryConstructor v2022.05-05

this constructor should be unified with CAP's terminal category

### CODE REVIEW

**Comment by zickgraf** [comment]
From looking at the code coverage I have two questions:

1. Why do the existing tests (e.g. the ones using MatrixCategory/CategoryOfRows) not include `AdditiveMonoidalCategoriesTest`?
2. Why can't the terminal category compute `LeftDistributivityExpanding` et al.?

**Comment by zickgraf** [comment]
> > 1. Why do the existing tests (e.g. the ones using MatrixCategory/CategoryOfRows) not include `AdditiveMonoidalCategoriesTest`?
> 
> I don't understand the question. `AdditiveMonoidalCategoriesTest` is currently only used in `MonoidalCategories/tst/TerminalCategoryMonoidal.tst` within the CAP_project repository.

Exactly, but I think it would be natural to also include `AdditiveMonoidalCategoriesTest` in the tests of MatrixCategory/CategoryOfRows, or am I missing something?

**Comment by mohamed-barakat** [comment]
I don't see a problem. Maybe you can reference your suggestion in a new issue.

**Comment by mohamed-barakat** [comment]
> 2. Why can't the terminal category compute `LeftDistributivityExpanding` et al.?

`TerminalCategoryWithMultipleObjects`() lies in the filter `IsAdditiveCategory`. So this is weird.

Note: The corresponding methods for [distributive cartesian categories](https://github.com/homalg-project/CAP_project/blob/master/CartesianCategories/gap/CartesianCategoriesDerivedMethods_extra.gi#L148-L164) and for [codistributive cocartesian categories](https://github.com/homalg-project/CAP_project/blob/master/CartesianCategories/gap/CocartesianCategoriesDerivedMethods_extra.gi#L148-L164) are installed.

**Comment by zickgraf** [comment]
> > 2. Why can't the terminal category compute `LeftDistributivityExpanding` et al.?
> 
> `TerminalCategoryWithMultipleObjects`() lies in the filter `IsAdditiveCategory`. So this is weird.
> 
> Note: The corresponding methods for [distributive cartesian categories](https://github.com/homalg-project/CAP_project/blob/master/CartesianCategories/gap/CartesianCategoriesDerivedMethods_extra.gi#L148-L164) and for [codistributive cocartesian categories](https://github.com/homalg-project/CAP_project/blob/master/CartesianCategories/gap/CocartesianCategoriesDerivedMethods_extra.gi#L148-L164) are installed.

You analysis in https://github.com/homalg-project/CAP_project/pull/913#issuecomment-1134660221 is correct. The difference to the situation for cartesian categories is that instead of the non-WithGiven versions the WithGiven versions (including the object) are listed here: https://github.com/homalg-project/CAP_project/blob/001bb26c300ad07fae89fad42dbe48efb4f634b5/CartesianCategories/gap/CartesianCategoriesProperties.gd#L16-L18

The correct solution is the following: `TerminalCategoryWithMultipleObjects` has to replace non-WithGiven operations by WithGiven operations and the corresponding objects in `list_of_operations_to_install` here: https://github.com/mohamed-barakat/CAP_project/blob/accef9d6e869737ce900cdc84c35704a7943a1ae/MonoidalCategories/gap/TerminalCategory.gi#L80 Hopefully this is something @TKuh tackles anyway while unifying `TerminalCategory` and `TerminalCategoryWithMultipleObjects`.

**Pull request merged**
