### PR TITLE
Introduce CAP_INTERNAL_GENERATE_DOCUMENTATION_FOR_CATEGORY_INSTANCES

### PR DESCRIPTION
**Pull request by zickgraf**
@mohamed-barakat @kamalsaleh Please check if this is sufficient as an MVP for now. See `FreydCategoriesForCAP/examples/generate_documentation.g` for how to call this and `FreydCategoriesForCAP/gap/CategoryOfRows.autogen.gd` for the result. Note: If you execute `FreydCategoriesForCAP/examples/generate_documentation.g` yourself, you will get warnings because some non-`CAP_project` packages have to be updated as well. The links in the online documentation are not yet adjusted.

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Look good for me. However, I am wondering why HigherHomologicalAlgebra appears in the list.

**Comment by zickgraf** [comment]
Because of this: https://github.com/homalg-project/HigherHomologicalAlgebra/blob/e9a7cf5e7bfb587dd645ac09da78d8a58f217bd0/ToolsForHigherHomologicalAlgebra/gap/CAP.gi#L9

`ToolsForHigherHomologicalAlgebra` is loaded via `ComplexesForCAP` which is a dependency of `QPA2` which is suggested by `FreydCategoriesForCAP`. Similarly, `Toposes` is loaded as a dependency of `FinSets` which is suggested by `FreydCategoriesForCAP`. This makes it hard to generate the documentation offline, because these packages are deliberately not included in the CI so one would have to exclude them locally, too :/

**Comment by zickgraf** [comment]
I have pushed an updated version:
1. It ignores operations from suggested packages because those are not always available and to work around the issues mentioned above.
2. It includes replacing the links for the online documentation, but I cannot test this locally, so we have to wait for the actual release.

If will merge this once the CI succeeds.

**Comment by mohamed-barakat** [comment]
`MorphismFromSourceToPushout` is linked to the first help occurrence which is

```
11.7 MorphismFromSourceToPushout and MorphismFromFiberProductToSink
```

**Comment by mohamed-barakat** [comment]
Unlike the [documentation of CategoryOfRows](https://homalg-project.github.io/CAP_project/FreydCategoriesForCAP/doc/chap5_mj.html#X7DA5FC5379955E0E) the [documentation of IntrinsicModules](https://homalg-project.github.io/IntrinsicModules/doc/chap1_mj.html#X7DA5FC5379955E0E) does not resolve the links correctly.

**Comment by zickgraf** [comment]
> Unlike the [documentation of CategoryOfRows](https://homalg-project.github.io/CAP_project/FreydCategoriesForCAP/doc/chap5_mj.html#X7DA5FC5379955E0E) the [documentation of IntrinsicModules](https://homalg-project.github.io/IntrinsicModules/doc/chap1_mj.html#X7DA5FC5379955E0E) does not resolve the links correctly.

I guess it's because the CAP documentation is not built. Can you add a step which builds the CAP documentation to the CI (i.e. call `make doc` in `CAP_project/CAP`) as a test?

**Comment by mohamed-barakat** [comment]
Excellent, it works, thank you very much.

**Comment by zickgraf** [comment]
Could you please open issues for the two points above, so we can properly keep track of this?

**Comment by zickgraf** [comment]
You can ignore my request above. Please test if https://github.com/homalg-project/CAP_project/pull/760 and https://github.com/homalg-project/PackageJanitor/commit/b2d942cb9b139dcbd0d44e6e9b2f0f999634fc12 fix your issues.

**Pull request merged**
