### PR TITLE
action category constructors now understand the option FinalizeCategory := false

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
@zickgraf: Do you understand the drop in coverage. It is happening with every new PR. In particular, I do not understand what he is comparing to.

**Comment by zickgraf** [comment]
I'm investigating this right at the moment :D I think the culprit is the nightly build using GAP master. My assumption is that GAP master reports more lines as covered than GAP 4.10, so every night the coverage rises and every pull request (running with GAP 4.10) drops it again.

**Comment by mohamed-barakat** [comment]
Thank you very much :)

**Comment by mohamed-barakat** [comment]
I just discovered `CAP_INTERNAL_RETURN_OPTION_OR_DEFAULT` two days ago and started using it in my new packages.

What about:
```
if CAP_INTERNAL_RETURN_OPTION_OR_DEFAULT( "FinalizeCategory", true ) = true then
```
It avoids a local variable and is safer than
```
if CAP_INTERNAL_RETURN_OPTION_OR_DEFAULT( "FinalizeCategory", true ) then
```

**Comment by mohamed-barakat** [comment]
Rereading your request you prefer a variable for better readability.

**Comment by sebastianpos** [comment]
Since you force pushed and I saw the changes by accident, I'll wait with the merge until you confirm that this is the intended state of the code.

**Comment by sebastianpos** [comment]
@mohamed-barakat 
is this PR ready to be merged?

**Comment by mohamed-barakat** [comment]
Yes please :)

**Pull request merged**
