### PR TITLE
Add tests to prevent https://github.com/homalg-project/CAP_project/is…

### PR DESCRIPTION
**Pull request by HereAround**
Add tests to prevent https://github.com/homalg-project/CAP_project/issues/746.

### CODE REVIEW

**Comment by zickgraf** [comment]
The CI succeeds, so this does not really seem to test the issue.

**Comment by zickgraf** [comment]
The difference is: Your example uses `AsFreydCategoryMorphism`, the example here uses `FreydCategoryMorphism`.

**Comment by HereAround** [comment]
Yes, it appears that this only affects objects and morphisms that were created via `AsFreydCategoryObject` and `AsFreydCategoryMorphism`. I just extended the tests accordingly.

**Comment by HereAround** [comment]
There we go. Now we have the expected failures.

**Comment by zickgraf** [comment]
Thanks! I will now retrigger the CI and merge if it turns green.

**Pull request merged**
