### PR TITLE
split CAP_INTERNAL_METHOD_NAME_RECORD

### PR DESCRIPTION
**Pull request by mohamed-barakat**
now CAP_INTERNAL_METHOD_NAME_RECORD is a posteriori populated by
five separate records:

* CAP_INTERNAL_METHOD_NAME_RECORD_IS_WELL_DEFINED
* CAP_INTERNAL_METHOD_NAME_RECORD_IS_EQUAL
* CAP_INTERNAL_METHOD_NAME_RECORD_IS_EQUAL
* CAP_INTERNAL_METHOD_NAME_RECORD_HOMOMORPHISM_STRUCTURE
* CAP_INTERNAL_METHOD_NAME_RECORD_RANDOM

This should allow an opt-in strategy in packages such as

* IntrinsicCategories
* AttributeCategoryForCAP
* CategoriesWithAmbientObjects
* FunctorCategories
* GradedCategories (new)

which create new categories out of given ones
by looping over the method records.

### CODE REVIEW

**Comment by zickgraf** [comment]
There is a clash in nomenclature: The list of diagram specifications of limits known to CAP is called `CAP_INTERNAL_METHOD_NAME_RECORD_LIMITS`. Its entries have a completely different structure than the entries of `CAP_INTERNAL_METHOD_NAME_RECORD`. However, in the nomenclature of this PR, `CAP_INTERNAL_METHOD_NAME_RECORD_LIMITS` sounds like the list of all entries of `CAP_INTERNAL_METHOD_NAME_RECORD` which are related to limits. So I think either the name `CAP_INTERNAL_METHOD_NAME_RECORD_LIMITS` or the names introduced in this PR should be changed.

**Comment by sebastianpos** [comment]
Could you elaborate on how this division helps for an opt-in strategy?

As I understand it, the problem with looping over the method record is that you never know which new basic operations there will be in the future. This problem is not prevented by a division in 5 records.

**Comment by mohamed-barakat** [comment]
I'll reply in October, this PR is not urgent for the moment. I'll keep rebasing it on master as I need it in what I am doing now.

**Comment by mohamed-barakat** [comment]
After discussions with @sebastianpos I will close this PR. I opened the draft PR #408 instead.

**Pull request closed without merging**
