### PR TITLE
Allow to pass the category as the first argument to any CAP operation

### PR DESCRIPTION
**Pull request by zickgraf**
~The first few commits are outsourced to #648.~

Technically, this PR is ready for review, but I would first like to discuss some choices I made / I want to make:

1. This PR is 100% backwards compatible for people using existing categories or writing their own categories.
2. It is not backwards compatible for people writing deriviations: They have to adapt their derivations to accept the category as the first argument (which should not be too hard, I think).
3. I have decided to add the category as the first argument "artificially" in the sense that it is prepended to the filter list in `InstallAdds.gi` and not in the method record. This might change, see below. (The motivation behind this approach was that I could change things step by step instead of having to change all pre functions, post functions, redirect functions, derivations etc. at once.)
4. In the current implementation, the category is passed on to all derivations and additionally to all primitively added functions of categories with `category!.category_as_first_argument` set to true.
5. None of this is documented yet. Of course I will write documentation as soon as everything is settled.
6. Question: Do we want to add the category argument to the method record (see point 3), or should we view this as an implementation detail for method selection? I vote for adding it to the method record as that fits the type theoretic approach, I think.
7. Question: Do we want to deprecate categories without `category!.category_as_first_argument` set to true (see point 4) in the future? I would vote yes, as adapting existing categories is not hard (just add `cat` as the first argument to all added functions).

### CODE REVIEW

**Comment by zickgraf** [comment]
Sorry, I forgot one question:
8. There are some convenience methods not part of the method record (e.g. functorials without WithGiven, `AdditiveInverse`, `PreCompose` for lists, etc.), so they do not automatically get versions with the category as first argument (e.g., one currently cannot write `PreCompose( cat, [ mor1, mor2 ] )`). Question: Should the convenience methods also get versions with the category as first argument? I would vote no, with the following argument: Either you want convenience, then you probaly do not want to pass the category, or you want speed/correctness/compilation, then you should not use any convenience. This would also mean that convenience methods should not be used in derivations. However, some things like `PreCompose` for lists could also simply be added to the method record, e.g. as `PreComposeList`, if needed.

**Comment by zickgraf** [comment]
Note: I'm still pushing to this branch because I have further changes based on the original PR. Once the discussion above is solved, I will of course split the PR up to make it reviewable.

**Comment by sebastianpos** [comment]
I agree with your votings w.r.t. questions 6-8.

**Comment by zickgraf** [comment]
This PR is now ready for review. Please review commits separately. See commit messages for details.

#### Structure of the PR

1. The first commit allows to call any CAP operation with the category as the first argument by artificially adding an appropriate filter in `InstallAdds.gi`.
2. This allows to remove method selection objects, `argument_list`, and many ops in subsequent commits.
3. The fifth commit actually adds the category as the first arguments to the method record, and passes it to all functions (pre, post, redirect, added). For backwards compatibility, primitively added functions are wrapped if category!.category_as_first_argument is not set to true.
4. The remaining commits should be self-explanatory by the commit message.

It make sense to always review the files on the following order: `AddFunctions.autodoc`, `MethodRecord.gi` (starting with `CAP_INTERNAL_ENHANCE_NAME_RECORD`), `InstallAdds.gi`, remaining files.

#### Documentation

I have only added a minimum of documentation as I expect things to change further. Since backwards compatibility is kept in most cases, this should not be a problem for ordinary users. I will open an issue for discussing some points regarding the documentation.

#### Notes

* The creation of the convenience methods without the category is very crude at the moment. I plan to update and generalize this in a future PR.
* Most derived methods still call operations without the category as the first argument. Changing this will be part of a future PR.
* I have not touched the io_types, so CategoryConstructor does not need adjustments regarding that point. @mohamed-barakat: I am open for discussions if the io_types should include the category or not.
* I will not be available for the next two weeks, so please do not merge until until then (or don't blame me for broken things :D ).

#### Compatibility

Packages have to be updated if they are
* using automatic post functions, redirect functions, or WithGiven derivations (suitable warnings will be raised when loading the package),
* adding derivations for methods in one of the updated method records (i.e. CAP, Freyd, MonoidalCategories; errors about a wrong number of arguments will be raised when loading the package),
* using prepare functions (I only know of SkeletalFinSets using this),
* relying on `argument_list` in a method record (suitable warnings will be raised when loading the package),
* loading FreydCategoriesForCAP in their tests, because #586 is finally fixed :-)

I will create PRs for FinSetsForCAP, Toposes, HigherHomologicalAlgebra and CategoryConstructor.

**Review by sebastianpos — APPROVED** [review]

**Comment by zickgraf** [comment]
I'm available again, so feel free to merge this PR any time you like :-)

**Comment by sebastianpos** [comment]
Okay, so as discussed 2 weeks ago, I'll merge this PR now :)

**Pull request merged**
