### PR TITLE
Monoidal structure for FreydCategoriesForCAP

### PR DESCRIPTION
**Pull request by HereAround**
This PR attempts to make the entire functionality of https://github.com/HereAround/CAPPresentationCategory available within FreydCategories for CAP. Changes include the following:

- monoidal structure implemented for FreydCategories
- extended display methods by "FullInformation"
- functions IsValidInputForFreydCategory and IsMonoidalStructurePresent have been added
- by use of these, the constructor of FreydCategory has been extended
- the example for graded rows/columns has been split to test their Freyd categories in a separated file
- test for FreydCategory( gradedColumns ) has been added
- bugfix in universal morphism from/into zero object of graded rows/column - arguments of this function were given in wrong order, leading to a "wrong number of columns/rows" error in extended tests

This is admittedly a fairly large PR. However, the major change is the implementation of the monoidal structure. The other points then derive from this change, except for the extended display methods. I have added them, since they mean only a minor change and we thus bring all the functionality of
https://github.com/HereAround/CAPPresentationCategory into FreydCategories with a single PR.

Among others we will need to discuss the following:
- well-definedness of associators
- is "rigid and symmetric closed monoidal structure" required for monoidal structure of Freyd category (-> method "IsMonoidalStructurePresent" need to be adjusted correspondingly)

We also need to think about "ProjectionOfBiasedWeakFiberProduct". Is this a required operation for any category that we want to build a FreydCategory upon?
- If yes, then the category cat at line 29 in the example file SnakeLemmaProof.g is not a valid input. 
- If no, then all uses of "ProjectionOfBiasedWeakFiberProduct" in FreydCategory.gi need to be grouped within an if-statement. Currently, e.g. line 681 in FreydCategory.gi is an exception to this - it installs (unless I am mistaken) "EpimorphismFromSomeProjectiveObjectForKernelObject" for all input categories by use of "ProjectionOfBiasedWeakFiberProduct".

Currently, I have therefore outcommented line 1535 in FreydCategories.gi. Once we find a solution for this, this has to be adjusted. Also, we should discuss the operations listed in lines 1517 to 1534 and 1583 to 1596 and identify a minimal set among these which are required by the underlying category to qualify as input category upon which we can define basic functionality/monoidal structure in its Freyd category.

[Examples, which test the monoidal structure implemented in this PR are not yet present in the examples. I would propose to use the tests of https://github.com/HereAround/PresentationsByProjectiveGradedModules. This however, is only possible after I have made this category available within FreydCategoriesForCAP...]

### CODE REVIEW

**Comment by sebastianpos** [comment]
@HereAround 

could you please rebase this PR to the current master?
There appear merge conflicts in the example file `GradedRowsAndColumns.g` and I'm not sure how to resolve them properly. Moreover, the tests fail since there were modifications in the Display method.

As a general strategy for the tests, I would recommend not to call `Display` (except it is exactly the Display function you want to test), but to only test output whose display is not likely to change at all (like booleans or integers).

**Comment by HereAround** [comment]
@sebastianpos 

I merged the current master into this branch and resolved the merge conflict in GradedRowsAndColumns.g.

You are right, I have made an adjustment to the display method. The change is two-fold:
- Whenever a object/morphism in the FreydCategory is being displayed, the message will say "object/morphism in a Freyd Category". Subsequently it will display the relation morphism/morphism datum.
- I have added a convenience method, which I call "FullInformation". It will display all objects/morphism of the underlying category, which are involved in the definition of an object/morphism in the Freyd Category. For example, for a morphism m in the FreydCategory it will display the morphism datum s of the source of m (i.e. Source( s ), Range( s ) and UnderlyingMatrix( s ) ). Likewise, for the morphism datum r of the range of m it will display Source( r ), Range( r ) and UnderlyingMatrix( r ). And last but not least, it will display the MorphismDatum( m ) by its UnderlyingMatrix. In playing with coherent sheaves, I found this very convenient.

I am happy to discuss these changes and adjust them. In any case, the tests in this PR were adjusted accordingly. I have checked this again after merging it with the current master - for me the tests pass without any error.

Regarding your strategy for the tests - I am happy to adjust the tests accordingly. Would you like to have these adjustments in this PR or should I open a new one?

**Comment by HereAround** [comment]
@sebastianpos:
After our last discussion, I have decided to split this large PR into several smaller ones, which are easier to merge. I have also embraced the opportunity to try out the cherry-picking in git.

The PRs in question should be discussed in the following order:
1. https://github.com/homalg-project/CAP_project/pull/323
2. https://github.com/homalg-project/CAP_project/pull/324
3. https://github.com/homalg-project/CAP_project/pull/325
4. https://github.com/homalg-project/CAP_project/pull/326
5. https://github.com/homalg-project/CAP_project/pull/327
6. https://github.com/homalg-project/CAP_project/pull/329
7. https://github.com/homalg-project/CAP_project/pull/315

Once these PRs are discussed, agreed and merged, FreydCategories should have obtained the full functionality of https://github.com/HereAround/CAPPresentationCategory with regards to monoidal structures. Subseququently, as explained above, tests for all these implementations can be literally taken from https://github.com/HereAround/PresentationsByProjectiveGradedModules. However, I postpone a PR for this, until at least part of the above have been discussed.

From my point of view, this PR can in principle be closed. For now, I leave it open, just in case we wish to discuss the splitting of this large PR. If this is not necessary, it can of course be closed immediately.

**Comment by HereAround** [comment]
Since we have worked through all of the above list of PRs but the last two, I think we can close this now.

**Pull request closed without merging**
