### PR TITLE
Add(Co)ImageObject, AddImageEmbedding/CoimageProjectionWithGiven*

### PR DESCRIPTION
**Pull request by mohamed-barakat**
to category of rows over a field

addresses https://github.com/homalg-project/CAP_project/pull/1194#discussion_r1042180284

### CODE REVIEW

**Comment by zickgraf** [comment]
Comparing the compiled code here to the code in https://github.com/homalg-project/CAP_project/pull/1194 shows many improvements: often objects are computed in a simpler way, and the isomorphisms actually translate between `BasisOfRows( matrix )` and `SyzygiesOfRows( SyzygiesOfColumns( matrix ) )` (i.e. as expected there would have been inconsistencies if viewing them as equal).

`(Inverse)MorphismFromCoimageToImage` uses `IsomorphismFromKernelOfCokernelToImageObject` and thus has some changes, too. It could potentially be simplified by the following logic template:
```
CapJitAddLogicTemplate(
    rec(
        variable_names := [ "A", "B", "C" ],
        src_template := "RightDivide( B, A ) * RightDivide( A, C )",
        dst_template := "RightDivide( B, C )",
    )
);
```
(I think, please double-check :D )

**Comment by mohamed-barakat** [comment]
I rebased this PR onto `master`, i.e., without the derivations from PR https://github.com/homalg-project/CAP_project/pull/1196. Several operations got higher weights and the compiled code for the following operations got more complicated:

* InverseMorphismFromCoimageToImageWithGivenObjects
* IsomorphismFromCoimageToCokernelOfKernel
* IsomorphismFromKernelOfCokernelToImageObject
* MorphismFromCoimageToImageWithGivenObjects

Without PR https://github.com/homalg-project/CAP_project/pull/1196 the suggested logic template had no effect.

**Comment by zickgraf** [comment]
That's because `IsomorphismFromKernelOfCokernelToImageObject` is derived as the inverse of `IsomorphismFromKernelOfCokernelToImageObject` instead of dually to `IsomorphismFromImageObjectToKernelOfCokernel`. With "dually" I mean using the universality of the kernel (`KernelLift`) instead of the universality of the image (`UniversalMorphismFromImage`). You should still do this as part of #1196, sorry if my comment there was misleading.

**Comment by zickgraf** [comment]
Ah, sorry, copy-paste mistake, it should read:

That's because `IsomorphismFromKernelOfCokernelToImageObject` is derived as the inverse of `IsomorphismFromImageObjectToKernelOfCokernel` instead of dually to the derivation of `IsomorphismFromImageObjectToKernelOfCokernel` which I linked in https://github.com/homalg-project/CAP_project/pull/1196.

**Comment by zickgraf** [comment]
For future reference: The CI failures, e.g. in Algebroids, show that `SyzygiesOfRows( SyzygiesOfColumns( m ) ) <> BasisOfRows( m )` in general as expected. So https://github.com/homalg-project/CAP_project/pull/1194 would indeed have lead to inconsistencies.

**Pull request merged**
