### PR TITLE
Take care of attributes in opposite cat

### LINKED ISSUE #495: Bug in OppositeCategories: No sync for categorical attributes
It seems that methods are well-derived in the opposite category, but attributes or properties such as range of homomorphism structure or commutative ring of some linear category  are not derived.

```
LoadPackage( "FreydCategoriesForCAP" );;
LoadPackage( "RingsForHomalg" );;

R := HomalgFieldOfRationalsInSingular() * "x,y,z";;
rows := CategoryOfRows( R );;
cat := Opposite( FreydCategory( rows ) );
DistinguishedObjectOfHomomorphismStructure( cat );
#! <A projective object in Freyd( Rows( Q[x,y,z] ) )>
RangeCategoryOfHomomorphismStructure( cat );
    Error, no method found!
```

### PR DESCRIPTION
**Pull request by sebastianpos**
closes #495

### CODE REVIEW

**Comment by sebastianpos** [comment]
@kamalsaleh 
If you confirm that this solves your issue, I'll merge this PR.

**Comment by kamalsaleh** [comment]
Adding `CommutativeRingOfLinearCategory` to the list of attributes would completely fix the issue.

**Comment by sebastianpos** [comment]
Right, I added the attribute.

**Comment by kamalsaleh** [comment]
Thank you very much :)

**Pull request merged**
