### PR TITLE
Split example files for graded rows/columns

### PR DESCRIPTION
**Pull request by HereAround**
Now we have:
- One file which tests the functionality of graded rows/columns.
- A second file which tests Freyd( ) of these categories. Here I have also added tests for Freyd( graded columns).
This PR anticipates tests for graded module presentations.

[Note that the second commit is a cherry pick of https://github.com/homalg-project/CAP_project/pull/324. It is crucial to ensure that the tests are running.]

There will be merge conflicts with https://github.com/homalg-project/CAP_project/pull/323. This is because the new display methods require that the tests (more precisely, the saved outputs that we compare the outputs of our computations to) be updates. Therefore, the test file GradedRowsAndColumns.g has been changed in both these PRs. To resole this merge conflict, delete all tests on FreydCategories from the test file GradedRowsAndColumns.g.

### CODE REVIEW

**Comment by sebastianpos** [comment]
I rebased to `master` and resolved the merge conflict as you proposed. However, note that the tests fail in `FreydCategoryOfGradedRowsAndColumns`, again due to `Display` issues.

**Comment by HereAround** [comment]
Sorry for this. Apparently I forgot to adjust the outputs in the tests of the FreydCategory of graded rows/columns. I am adjusting this right now. Fix to come within the next hour...

Also, I agree that failed tests due to changed Display-methods are fairly annoying. I will propose a PR to correct for this in the next few days. For now, if you agree, I would propose to migrate the monoidal structure to FreydCategories first, and then focus on this "Display-issue". Do you agree?

**Comment by sebastianpos** [comment]
Yes, I agree. Thank you.

**Comment by HereAround** [comment]
With the above commit, the tests complete without error again.

**Pull request merged**
