### PR TITLE
added CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsCategoryWithDecidable(Co)Lifts

### PR DESCRIPTION
**Pull request by mohamed-barakat**
* added corresponding properties to `CAP_INTERNAL_CATEGORICAL_PROPERTIES_LIST`
* AddIsLiftable/IsColiftable to `CAP_INTERNAL_CONSTRUCTOR_FOR_TERMINAL_CATEGORY` as they are explicitly excluded as boolean functions
* moved example files from `MonoidalCategories` -> `CAP` (since `LinearAlgebraForCAP` is loaded by other tests I explicitly load `MonoidalCategories` in these files)

resolves https://github.com/homalg-project/CAP_project/issues/1168

### CODE REVIEW

**Comment by zickgraf** [comment]
Aaah, you found the missing example chunks :D Perfect!

For a clean and generic handling of `IsLiftable` and `IsColiftable` (and even `IsCongruentForMorphisms`) I suggest adding them as derivations with `CategoryFilter := IsTerminalCategory`. For `IsCongruentForMorphisms` this would resemble the situation for thin categories in Locales (see https://github.com/homalg-project/Locales/issues/112).

**Comment by zickgraf** [comment]
Btw: When loading Locales, the terminal category can compute `IsLiftable` and `IsColiftable`. Maybe `IsThinCategory` is such a basic concept that it should live inside CAP?

**Comment by mohamed-barakat** [comment]
> For a clean and generic handling of `IsLiftable` and `IsColiftable` (and even `IsCongruentForMorphisms`) I suggest adding them as derivations with `CategoryFilter := IsTerminalCategory`.

Done.

**Comment by mohamed-barakat** [comment]
> Btw: When loading Locales, the terminal category can compute `IsLiftable` and `IsColiftable`. Maybe `IsThinCategory` is such a basic concept that it should live inside CAP?

This is indeed the next PR 😂 You are reading my thoughts.

**Comment by zickgraf** [comment]
> > For a clean and generic handling of `IsLiftable` and `IsColiftable` (and even `IsCongruentForMorphisms`) I suggest adding them as derivations with `CategoryFilter := IsTerminalCategory`.
> 
> Done.

Those derivations will become obsolete once you add `IsThinCategory` with the corresponding derivations to CAP. Do you still want to have them in this PR?

**Comment by mohamed-barakat** [comment]
> > > For a clean and generic handling of `IsLiftable` and `IsColiftable` (and even `IsCongruentForMorphisms`) I suggest adding them as derivations with `CategoryFilter := IsTerminalCategory`.
> > 
> > 
> > Done.
> 
> Those derivations will become obsolete once you add `IsThinCategory` with the corresponding derivations to CAP. Do you still want to have them in this PR?

Why should `IsLiftable` and `IsColiftable` become obsolete for `IsThinCategory`?

**Comment by zickgraf** [comment]
I mean "obsolete" in the sense of "covered by more generic derivations" (For the details, create a terminal category with Locales loaded and trace back the derivation of `IsLiftable`. It's fun :D ). Since we want to use the terminal category to test derivations, we should not override generic derivations by special ones here, I think.

**Comment by mohamed-barakat** [comment]
> I mean "obsolete" in the sense of "covered by more generic derivations" (For the details, create a terminal category with Locales loaded and trace back the derivation of `IsLiftable`. It's fun :D ). Since we want to use the terminal category to test derivations, we should not override generic derivations by special ones here, I think.

I was only planning to move the declaration of `IsThinCategory` to `CAP`, maybe this is why I did not understand your reply. In any case, further improvements can be gradually done in further PRs. And we need to talk about a clean strategy for moving existing code in other packages to `CAP`.

**Pull request merged**
