### PR TITLE
d&a PostInverse/PreInverseForMorphisms together with two derivation methods

### PR DESCRIPTION
**Pull request by kamalsaleh**
These are, up to their names, copy & paste of the same methods in `CategoryConstructor` package:

https://github.com/homalg-project/CategoryConstructor/blob/5b33ddfbefc58f4923fe8ff74fd4337e349e5209/gap/ToolsMethodRecord.gi#L47-L61

### CODE REVIEW

**Review by zickgraf — APPROVED** [review]
Thanks, only one small typo.

**Review by mohamed-barakat — CHANGES_REQUESTED** [review]
I would suggest outsourcing the code in `CategoryConstructor`, i.e., dropping the suffix `ForMorphisms`.

**Comment by zickgraf** [comment]
> I would suggest outsourcing the code in `CategoryConstructor`, i.e., dropping the suffix `ForMorphisms`.

I think the analogy to `InverseForMorphisms` is a good thing.

**Comment by mohamed-barakat** [comment]
> I think the analogy to `InverseForMorphisms` is a good thing.

Right, I agree.

**Review by mohamed-barakat — DISMISSED** [review]

**Comment by kamalsaleh** [comment]
I agree with Fabian in keeping the analogy. This would also reduce the interference with other packages that might declare these `PreInverse `and `PostInverse`, e.g., `Modules `or `GradedModules`. 

We can keep the installation name as is while introducing new "convenience" operations/attribute? similar to `InverseForMorphisms` & `Inverse`.

**Review by zickgraf — APPROVED** [review]

**Pull request merged**
