### PR TITLE
fixed docu of MorphismFromFiberProductToSinkWithGivenFiberProduct

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
The list of given arguments was a copy-paste mistake.

**Comment by zickgraf** [comment]
Note: This is also included in #375. But I don't think this causes merge conflicts or at least I hope :D.

**Comment by mohamed-barakat** [comment]
Then I will close it, what do you think?

**Comment by sebastianpos** [comment]
Thank you :-)

**Pull request merged**
