### PR TITLE
let Display print InfoOfInstalledOperationsOfCategory

### PR DESCRIPTION
**Pull request by mohamed-barakat**
and removed by now obsolete CAP_INTERNAL_INSTALL_PRINT_FUNCTION

### CODE REVIEW

**Review by zickgraf — CHANGES_REQUESTED** [review]

**Review by zickgraf — DISMISSED** [review]

**Comment by mohamed-barakat** [comment]
The CI on GitHub passed but their status was not updated.

**Comment by zickgraf** [comment]
The CI was triggered (and succeeded) for 041e7f948bc448c4ce398e09e6daf5b2a99b25ab, but not for bd68ada485e431c5cbf3c380ca293ebdebeb0d67. Can you force-push once more?

**Comment by mohamed-barakat** [comment]
> The CI was triggered (and succeeded) for [041e7f9](https://github.com/homalg-project/CAP_project/commit/041e7f948bc448c4ce398e09e6daf5b2a99b25ab), but not for [bd68ada](https://github.com/homalg-project/CAP_project/commit/bd68ada485e431c5cbf3c380ca293ebdebeb0d67). Can you force-push once more?

Done.

**Comment by mohamed-barakat** [comment]
I forgot to adapt the version numbers :(

**Pull request merged**
