### PR TITLE
Allow several categories of rows/cols

### LINKED ISSUE #420: Allow several categories of Rows/Cols for one single ring
At the moment, the category of rows/cols is an attribute of the ring.
I'm planning to change that in order to allow multiple versions of the category of rows/cols.
In particular, there may coexist a "clever" and a "workhorse" version within the same session.

I will provide a PR in the near future.

### PR DESCRIPTION
**Pull request by sebastianpos**
Closes #420

### CODE REVIEW

**Comment by sebastianpos** [comment]
@mohamed-barakat 

please test if this change doesn't affect your packages building on rows/cols too much.

**Comment by mohamed-barakat** [comment]
@sebastianpos: I have to adapt `ZariskiFrames` to use the new two-argument constructor `AsCategoryOfRowsMorphism` instead of the deprecated one-argument version. I won't come to it this week.

**Comment by sebastianpos** [comment]
If you are nevertheless okay with these changes, I would like to merge this soon.

**Comment by mohamed-barakat** [comment]
Merging it will break `ZariskiFrames` but this is OK since I will work on `ZariskiFrames` by the end of the week.

**Comment by sebastianpos** [comment]
Ok.

**Pull request merged**
