### PR TITLE
Use `CreateCapCategoryWithDataTypes` at more places

### PR DESCRIPTION
**Pull request by TKuh**
In particular, get rid of `AddObjectRepresentation` and `AddMorphismRepresentation`.

Step towards #1269.

### CODE REVIEW

**Comment by zickgraf** [comment]
Thanks, very nice :-) Can you please create a PR which contains only those commits which do not add new filters or rename filters? E.g. https://github.com/homalg-project/CAP_project/pull/1370/commits/5801c34d7b8fb2a9c1ddeee9fe0d338bbb0fc507. This simplifies the review.

**Comment by TKuh** [comment]
> Thanks, very nice :-) Can you please create a PR which contains only those commits which do not add new filters or rename filters?

Sure, done. :)

General question: it seems to me, that the current naming convention for object/morphism filters is `IsObjectIn*` and `IsMorphismIn*`. Is that right? If yes, are you fine with renaming filters in that way (I did not dare to touch `FreydCategoriesForCAP` though)? It's of course not a big deal, but reads nicer.

**Review by zickgraf — APPROVED** [review]
Thanks!

**Comment by zickgraf** [comment]
> General question: it seems to me, that the current naming convention for object/morphism filters is `IsObjectIn*` and `IsMorphismIn*`. Is that right? If yes, are you fine with renaming filters in that way (I did not dare to touch `FreydCategoriesForCAP` though)? It's of course not a big deal, but reads nicer.

We do not really have an official convention (yet). So I suggest to not do a general rename as part of this series of PRs, except where there is an explicit reason (e.g. if you introduce a new category filter I can imagine that sometimes adjusting the object and morphism filters would be natural).

**Pull request merged**
