### PR TITLE
changed "Opposite of ..." -> "Opposite( ... )"

### PR DESCRIPTION
**Pull request by mohamed-barakat**
reason: converging towards suggestive names of constructors should improve user experience

### CODE REVIEW

**Comment by zickgraf** [comment]
While we're at it: Should the constructor be named `OppositeCategory`?

**Comment by mohamed-barakat** [comment]
> While we're at it: Should the constructor be named `OppositeCategory`?

Aren't you using `OppositeCategory` in the sense of `WasCreatedAsOppositeCategory`? If so, then we need to rename
* OppositeCategory -> WasCreatedAsOppositeCategory
* Opposite -> OppositeCategory

Correct?

**Comment by zickgraf** [comment]
> Aren't you using `OppositeCategory` in the sense of `WasCreatedAsOppositeCategory`?

I'm currently using `OppositeCategory` as an attribute of a category which `WasCreatedAsOppositeCategory`. But I don't think this is actually needed anymore, and if it is, we can always find another name (worst case: the generic term `UnderlyingCategory`).

**Comment by mohamed-barakat** [comment]
I suggest doing this as a subsequent commit. It doesn't look trivial.

**Pull request merged**
