### PR TITLE
added convenience for ModelingObject/ModelingMorphism

### PR DESCRIPTION
**Pull request by mohamed-barakat**
closes https://github.com/homalg-project/CAP_project/issues/1266

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
The suggested warnings are still missing.

**Comment by zickgraf** [comment]
> The suggested warnings are still missing.

You could use the warning mentioned in https://github.com/homalg-project/CAP_project/issues/1266#issuecomment-1449561083 (replacing the first half of the sentence by the context here).

**Review by zickgraf — CHANGES_REQUESTED** [review]
The changes themselves are fine, but please move them to `ReinterpretationOfCategory.gi`.

**Comment by mohamed-barakat** [comment]
> The changes themselves are fine, but please move them to `ReinterpretationOfCategory.gi`.

Done.

**Review by zickgraf — APPROVED** [review]

**Comment by mohamed-barakat** [comment]
I was not notified by email when you merged. Weird.

**Comment by zickgraf** [comment]
> I was not notified by email when you merged. Weird.

Now the notifications arrive:

https://www.githubstatus.com/

> We have mitigated the issue impacting the delivery of notifications, and are working to deliver the backlog of notifications.

**Comment by mohamed-barakat** [comment]
Indeed :)

**Pull request merged**
