### PR TITLE
AddObjectDatum/AddMorphismDatum in AdditiveClosure

### PR DESCRIPTION
**Pull request by mohamed-barakat**
I need this in LazyCategories for a uniform behavior of the categories in the tower

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
`Algebroids/examples/PrecompileAdditiveClosureOfAlgebroid.g` fails with the PR.

**Comment by zickgraf** [comment]
> I need this in LazyCategories for a uniform behavior of the categories in the tower

Before using `ObjectConstructor` et al. for uniform behavior we should discuss https://github.com/homalg-project/CAP_project/issues/780.

In any case, when adding `*Datum` one should also add `*Constructor`, as otherwise there is not really a specification.

**Comment by zickgraf** [comment]
@mohamed-barakat Now that #780 is solved, this PR can be merged after rebasing and adding the constructors.

**Review by zickgraf — APPROVED** [review]
Thanks!

**Pull request merged**
