### PR TITLE
d&i AffineDimension for IsGradedLeftOrRightPresentation

### PR DESCRIPTION
**Pull request by mohamed-barakat**
This is now possible:

FullSubcategoryByMembershipFunction( Sgrmod, M -> AffineDimension( M ) <= 0 );

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
Ping?

**Comment by sebastianpos** [comment]
What exactly do you mean by the affine dimension of a graded module?

**Comment by mohamed-barakat** [comment]
It is the Krull dimension of the annihilator ideal of the underlying nongraded module.

**Comment by sebastianpos** [comment]
But then I suppose there should be a distinction in the code between left and right modules.

**Comment by mohamed-barakat** [comment]
Yes, you are right, I mistakenly used the general filter for declaration in the installation. Will fix.

**Comment by mohamed-barakat** [comment]
Fixed and forced pushed the changes.

**Comment by sebastianpos** [comment]
Thanks. Could you also please update the documentation (i.e., describe what the affine dimension is) and provide an error handling for the case when the ring `ring_for_representation_category` is not commutative?

**Comment by mohamed-barakat** [comment]
Done.

**Pull request merged**
