### PR TITLE
dual_operation/dual_arguments_reversed for IsHomSetInhabited

### PR DESCRIPTION
**Pull request by mohamed-barakat**

### CODE REVIEW

**Comment by mohamed-barakat** [comment]
I don't understand why no tests are triggered.

**Comment by zickgraf** [comment]
> I don't understand why no tests are triggered.

GitHub Actions have a major outage: https://www.githubstatus.com/

**Comment by mohamed-barakat** [comment]
Ah, thanks :)

**Comment by zickgraf** [comment]
GitHub Actions seem to be operational again, but the job is stuck (I cannot even cancel it) -> you probably need to force-push.

**Comment by mohamed-barakat** [comment]
Done.

**Review by sebastianpos — APPROVED** [review]

**Pull request merged**
